version: "3.6"

services:
  # clickhouse:
  #   image: yandex/clickhouse-server
  #   container_name: clickhouse-server
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #   ports:
  #     - "${CLICKHOUSE_HTTP_PORT:-8123}:8123" # HTTP port
  #     - "${CLICKHOUSE_NATIVE_PORT:-9000}:9000" # Native port
  #   environment:
  #     - CLICKHOUSE_USER=myuser
  #     - CLICKHOUSE_PASSWORD=mypassword 
  #     - CLICKHOUSE_SERVER_MAX_EXECUTION_TIME=12000

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_click
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "${KAFKA_PORT:-9092}:9092" # Kafka port
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.43
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # чтоб в ручную не создавать топик
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_click:2182'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_COMPACT: "true"
      CONNECT_OFFSET_STORAGE_COMPACT: "true"
      CONNECT_STATUS_STORAGE_COMPACT: "true"

  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - broker
      - zookeeper
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper_click:2182
      KAFKA_CLUSTERS_0_NAME: local2
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 'kafka:29092'

  debezium:
    image: debezium/connect:2.6
    environment:
      BOOTSTRAP_SERVERS: 'kafka:29092'
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    ports:
      - 8083:8083

  # schema-registry:
  #   image: confluentinc/cp-schema-registry
  #   container_name: schema-registry
  #   hostname: schema-registry
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
  #     SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
  #   depends_on:
  #     - broker

volumes:
  zookeeper_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/vladislavpustobaev/zookeeper_data:/var/lib/zookeeper/data
  # clickhouse_data:
  #     driver: local
  #     driver_opts:
  #       type: none
  #       o: bind
  #       device: /Users/vladislavpustobaev/clickhouse_data