CREATE TABLE IF NOT EXISTS user_data_queue (
        uuid String,
        createdAt String,
        dateAction Nullable(String),
        ban UInt8,
        reg UInt8,
        dateReg Nullable(String),
        idClient UInt32,
        email Nullable(String),
        clickId Nullable(String),
        utmSource Nullable(String),
        utmMedium Nullable(String),
        utmCampaign Nullable(String),
        wd UInt8,
        wdSum Nullable(Float64),
        dep UInt8,
        depSum Nullable(Float64),
        ftdSum Nullable(Float64),
        dateFtd Nullable(String),
        sDepSum Nullable(Float64),
        dateSDep Nullable(String),
        tDepSum Nullable(Float64),
        dateTDep Nullable(String),
        idOperation Nullable(String),
        pSystemLag Nullable(UInt32),
        pSystemId Nullable(UInt32),
        dateFirstSpin Nullable(String),
        dateLastSpin Nullable(String),
        newGamer Nullable(UInt8),
        gamer Nullable(UInt8),
        gameUuid Nullable(String),
        bets Nullable(Float64),
        wins Nullable(Float64),
        refunds Nullable(Float64),
        rollbacks Nullable(Float64),
        ggr Nullable(Float64),
        idTicket Nullable(String),
        countOfSpins Nullable(UInt32),
        missInGame Nullable(UInt32),
        currency Nullable(String),
        currencyRate Nullable(Float64)
) ENGINE = Kafka SETTINGS
            kafka_broker_list = 'kafka:29092,192.168.0.43:9092',
            kafka_topic_list = 'analytics',
            kafka_group_name = 'analytics',
            kafka_format = 'JSONEachRow',
            kafka_num_consumers = 1,
            kafka_max_block_size = 1;